### ISSUE TITLE
Error in SV-length-plot.py

### ISSUE THREAD

**Issue by tdido** [wdecoster/nano-snakemake#10]
Hey Wouter.

I'm getting an error in SV-length-plot.py on this line:

https://github.com/wdecoster/nano-snakemake/blob/cd5a47a8d913487aa278b7f76dac9ef3559a623f/scripts/SV-length-plot.py#L19

The error is:
```
IndexError: index 0 is out of bounds for axis 0 with size 0
```

And it's caused by this line:
```
chr4    49582713        pbsv.CNV.45202  A       <CNV>   .       NearReferenceGap        SVTYPE=cnv;END=49711933;SVLEN=129220    CN      18
```
The cause is the `gt_types` list being empty. Would it make sense to add a condition to the if to check for the length of the list? Is there a better solution?

Thanks!

**Comment by wdecoster** [comment]
Hi Tomás,

Thanks for reporting this. The gt_types array contains the zygosities of the samples in the vcf (0/0-0/1-1/1), but is indeed empty when the vcf does just have the variant positions, without genotypes. 

I just pushed a fix to the script, which assumes that a VCF without genotypes contains all variant positions, without checking the gt_types if the sample effectively has a variant genotype. Please let me know if that does not solve your issues.

Cheers,
Wouter

**Comment by tdido** [comment]
Yes, that works. Thanks!
