### ISSUE TITLE
Instruction regarding submitted data in ENA

### ISSUE THREAD

**Issue by vahidAK** [wdecoster/nano-snakemake#13]
Hi @wdecoster ,
In the paper (Structural variants identified by Oxford Nanopore PromethION sequencing of the human genome) you mentioned you have sequenced on 5 promethion flowcells however in ENA (PRJEB26791) it seems there are more than that. Are they redundant? or they all are separate runs?
Thanks,
Vahid.

**Comment by wdecoster** [comment]
There are 5 PromethION fast5 sets and the rest is either MinION data of the same individual or different versions of the basecaller in fastq format. Let me know if something is unclear

**Comment by vahidAK** [comment]
Thanks, @wdecoster 
I could not find the base caller version and model used for ERR2585112-5.
Could you please let me know what base caller and model were used for them?

**Comment by wdecoster** [comment]
That's an old version of Guppy, for sure older than 1.4.0, and I would not advise anyone to still use these. If it's really important for you to know which version it is I can try to find it...
The model was just the DNA 9.4.1 for PromethION. Back then there was no choice between HAC or FAST basecalling.

The most recent base calls which we shared online are those in https://www.ebi.ac.uk/ena/data/view/SAMEA5418551

**Comment by vahidAK** [comment]
Thanks, @wdecoster, No it is not important. I will use newer versions.  
Sorry, but I had another question. The fast5 files are under these accessions: ERR3046934-8
I was wondering the order of fast5 accessions is equivalent to the order of the new base called fastqs?  
ERR3046934 == ERR3219853  
ERR3046935 == ERR3219854  
ERR3046936 == ERR3219855  
ERR3046937 == ERR3219856  
ERR3046938 == ERR3219857

**Comment by wdecoster** [comment]
That should be the case yes.


If you check the filename of the files in the column Submitted files (FTP) you'll see things like
ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR321/ERR3219853/20180413.fastq.gz
ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR304/ERR3046934/20180413_NA19240_run0.tar.gz

That contains the name of the dataset (which is the date it was sequenced, in this case, 20180413).
