### ISSUE TITLE
Minimap2 - Command not found

### ISSUE THREAD

**Issue by EEsdaile** [wdecoster/nano-snakemake#15]
Hi again Wouter, 

I feel so close to this working but now I'm getting an error saying:
/bin/bash: line 1: minimap2: command not found   
Error in rule minimap2_align:   
    jobid: 10   
    output: out/minimap2/alignment/sample.bam   
    log: log/minimap2/sample.log   

Attached is my log file   
[nano-snakemake.txt](https://github.com/wdecoster/nano-snakemake/files/4897667/nano-snakemake.txt)   

What have I done wrong this time?   

Thanks,    

Elizabeth

**Comment by wdecoster** [comment]
I think you should either make sure that minimap2 is installed or execute snakemake with the `--use-conda` flag.

**Comment by EEsdaile** [comment]
Got it! For some reason it wasn't activating Minimap2, but when I told the slurm run file to activate minimap2 it looks like it worked. Thanks again. Looks like it's running successfully.
