### ISSUE TITLE
Rule: minimap2_align

### ISSUE THREAD

**Issue by Nazeeefa** [wdecoster/nano-snakemake#2]
Hi Wouter,

Thank you for creating and sharing the pipeline, I appreciate the work! :)

Just wondering, how come you used --MD flag? as compared to, for example, using "-ax map-ont --MD" for your dataset?

I appreciate your time, and thanks again for your work!

Cheers,
Nazeefa
p.s. sorry if my question sounds silly

**Comment by wdecoster** [comment]
Hi Nazeefa,

As described [here](https://github.com/lh3/minimap2#use-cases) the default setting of minimap2 is `-x map-ont`. Therefore this part was omitted from the command, and only `--MD` was used. But I agree that it would be better to explicitly write `-x map-ont` to make everything clear, so I'll change that.

Hope that answers your question.

Wouter

**Comment by Nazeeefa** [comment]
Thanks, Wouter! Before I close the issue, I was wondering how did --MD benefit your alignment analysis in particular? I understand it is used for SNP/Indel calling.

Cheers,
Nazeefa

**Comment by wdecoster** [comment]
It does not alter the alignment, but it is required information for Sniffles, for variant calling.
