### ISSUE TITLE
Recompute --MD

### ISSUE THREAD

**Issue by Nazeeefa** [wdecoster/nano-snakemake#3]
Hi Wouter,

It may be a good idea to mention the step for recomputing --MD tag. Sorry if it's not necessary or if it's already mentioned (I can't seem to find it).

Cheers,

Nazeefa

**Comment by wdecoster** [comment]
Hi Nazeefa,

Hmm I'm not sure if I follow what you mean here. Where would it be necessary? minimap2 adds the MD tag during the alignment because I specify the `--MD` option on the command line. ngmlr adds the MD tag by default. Therefore no recomputing is required, I believe.

Cheers,
Wouter

**Comment by Nazeeefa** [comment]
Hi Wouter,

You are right. I checked again and it's not required at all. Sorry, I got confused because I wasn't receiving a proper output from Sniffles hehe :)

Thanks anyway.

Cheers,
Nazeefa

**Comment by wdecoster** [comment]
You're welcome! Let me know if there is anything else.
