### ISSUE TITLE
annotation files

### ISSUE THREAD

**Issue by ramcn** [wdecoster/nano-snakemake#5]
Hello Wouter,

Thanks a lot for publishing your methods. It is really useful.

I am trying to replicate your experiments with nanopore na12878 dataset. I have replicated the required conda environment and downloaded the Grch38 and fastq files. But stuck with finding the right annotation files. Particularly the ones mentioned below which are used by the setup.

1. annotation.bed.gz  referenced in config.yaml
2. and other annotation files referenced in vcfanno_conf.toml 

Would it be possible to share these files or give me some pointers to find them?

Thank you,
Ram

**Comment by wdecoster** [comment]
Hi Ram,

The easiest is to download these from the UCSC table browser at https://genome.ucsc.edu/cgi-bin/hgTables
You can select the features you want and download those as a bed file.

Let me know if you encounter an issue with that.

Cheers,
Wouter

**Comment by ramcn** [comment]
Yeah I tried using it. But couldn't figure out the right attributes (track, table etc). to select for each of the annotations as I am not much familiar with using it.

Could you please let me know what are the attributes to select in hgtables for annotation.bed.gz  in config.yaml and other file referenced in  vcfanno_conf.toml.

Thank you,
Ram

**Comment by wdecoster** [comment]
My annotation files are meant as an example, and you may or may not want to add additional files depending on how you want to annotate your variants. `/path/to/database/annotation.bed.gz` is just used by NanoSV "for coverage depth calculations". You could, for example, want to add other repeat annotations such as repeatmasker.

For exons and genes you should look at `group: genes and gene predictions`, `track: NCBI refseq` or maybe `track: GENCODE v29` if you like that annotation better, `Table: RefSeq All (...)`. Region would be `genome`. Output format should be `bed`, probably best to get it gzip compressed.

The dgv information is available under `group:variation` and `track:DGV Struct Var`.

The genomicSuperDups are under `group:Repeats` and `track:Segmental Dups`.
