### ISSUE TITLE
sv-length-plot.py error

### ISSUE THREAD

**Issue by wangjiawen2013** [wdecoster/nano-snakemake#6]
Dear,
When I ran the following code chunk:
 scripts/SV-length-plot.py sniffles_calls/ERR2631600.vcf --output test/test.png --counts test/test.counts
The error occurs:
Traceback (most recent call last):
  File "scripts/SV-length-plot.py", line 120, in <module>
    main()
  File "scripts/SV-length-plot.py", line 41, in main
    output=args.output)
  File "scripts/SV-length-plot.py", line 70, in make_plot
    key=lambda x: sorter.index(x[0])))
ValueError: not enough values to unpack (expected 2, got 0)

Do you know what happened ?

Best regards

**Comment by wdecoster** [comment]
Based on the directory names (sniffles_calls) I assume your vcf contains only the variants and their positions, but no genotypes for that sample. If you open the vcf file you will probably see that all variants have `GT=./.`. You can obtain genotypes from sniffles using either the `--Ivcf` or `--genotype` options.

Currently, sv-length-plot.py will only show variants which are genotyped. I could rewrite the code to optionally just plot all variants, regardless of genotype.

Does that answer your question?

**Comment by wangjiawen2013** [comment]
Thanks, it's just so.
I don't know much about the parameters --Ivcf， I know it's best to ask sniffle's author, however could you explain it to me ?

**Comment by wdecoster** [comment]
I'll do my best, but maybe @fritzsedlazeck can confirm or add some. With `--Ivcf` you can specify a vcf file of SVs, which will then be used in Sniffles to genotype those. You could for example using sniffles to identify variants from a population or cohort, and then genotype all those which are identified in each individual. See also [this wiki page](https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population). If you are only using one sample then `--Ivcf` equivalent to `--genotype`.

**Comment by Nazeeefa** [comment]
Hi Wouter,

I get the same error, but it's when I try to get stats and plot for one SV type for a specific chromosome - e.g. I was just curious to see how many nucleotides are affected by insertions located at chromosome 1. Anyway, the vcf file (I have) contains genotyped variants.

I appreciate your advice and time.

Cheers,
Nazeefa

**Comment by wdecoster** [comment]
Hi Nazeefa,

Which specific SV type, then?

Regards,
Wouter

**Comment by Nazeeefa** [comment]
Hi Wouter,

I mentioned it in my comment (insertions) :)

**Comment by wdecoster** [comment]
I won't be able to look into this before Monday. Can you perhaps share the vcf which gave this issue? That would make debugging easier.

Thanks

**Comment by Nazeeefa** [comment]
No worries and there you go! it's just a small test file.
[sniffles_file1.vcf.zip](https://github.com/wdecoster/nano-snakemake/files/3191570/sniffles_file1.vcf.zip)
Cheers! I appreciate your time :)

**Comment by wdecoster** [comment]
I filtered your vcf file to get insertion for chromosome 1 with this:
`cat <(grep '^#' sniffles_file1.vcf) <(grep -v '^#' sniffles_file1.vcf | grep -w chr1 | grep INS)`

Using `SV-length-plot.py` doesn't return any errors on that file...

**Comment by Nazeeefa** [comment]
Thanks, but I was trying to figure if it is possible to use the script to get total size for each SV type located at each chromosome. I understand if it's too much to ask, thanks anyway!

**Comment by wdecoster** [comment]
I don't think I am going to implement that. But you could write a loop to get that done, something like (untested):

```
for chr in $(grep -v '^#' variants.vcf | cut -f1 | sort -u)
do
bcftools view variants.vcf -o variants_${chr}.vcf $chr
python SV-length-plot.py variants_${chr}.vcf -c SV-counts-${chr}.txt -o SV-counts-${chr}.png
done
```

**Comment by wdecoster** [comment]
I'll now close this, but please let me know if there is anything else I can help you with.
