### ISSUE TITLE
sorting vcf

### ISSUE THREAD

**Issue by wangjiawen2013** [wdecoster/nano-snakemake#7]
Dear,
I am follow your work on bioRxiv paper, does "vcf-sort" and "bcftools sort" have the same function ?

**Comment by wdecoster** [comment]
Hmm I think so, but there definitely was a reason why I did not use `bcftools sort` everywhere. Maybe it works now, I'm not 100% sure. I would definitely prefer `bcftools sort`.

For what it's worth, I have added the `vcf-sort.pl` script to this repository at https://github.com/wdecoster/nano-snakemake/blob/master/scripts/vcf-sort.pl
If you download it somewhere, and put a softlink or copy with name `vcf-sort` in your $PATH, all should be fine:

e.g. 

`ln -s ~/Downloads/vcf-sort.pl ~/bin/vcf-sort`
