### ISSUE TITLE
Cannot create environment with `environment.yaml`

### ISSUE THREAD

**Issue by BCArg** [wdecoster/nano-snakemake#9]
When I try to create a virtual env to run the pipeline with
```
conda env create -n nano-snakemake -f environment.yaml
```

I am getting:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libtiff==4.0.10=h648cc4a_1001
  - qt==4.8.7=2
  - libssh2==1.8.0=1
```

Any changes to `environment.yaml` that might get this fixed?

Thanks in advance

**Comment by wdecoster** [comment]
I'll look into it... but I don't know when I'll have the time :)

**Comment by Nazeeefa** [comment]
Maybe those packages need to be added under pip section in `.yml` file..and, in case that doesn't work, renaming of packages excluding version (e.g. changing `qt==4.8.7=2` to `qt`) might help. Also, before creating virtual env, make sure to run `conda update --all` to update packages.

**Comment by tdido** [comment]
Using package versions in conda environments is tricky: unfortunately, conda is not future-proof right now and as some versions disappear from the repository you can get these problems.

In this case, you can get away with removing the versions from the environment.yaml file. See [this link](https://github.com/tdido/nano-snakemake/blob/master/environment.yaml).

**Comment by wdecoster** [comment]
Hi Tomás,

That's unfortunate indeed, and good to hear things work without versions. I'd be happy to merge your pull request and please go ahead if there are other improvements you have in mind.

Thanks,
Wouter

**Comment by tdido** [comment]
Hey Wouter.

Yes, I'm setting up the pipeline and working on some changes. As soon as I have a working version I'll let you know, and if you're interested I'll create a PR.
